# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-19 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(help_text=' End First Day of the event', verbose_name='End Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(help_text='Start Day of the event', verbose_name='Start Day of the event'),
        ),
    ]
